# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+e0778a3
loader_version=0.19.5

# Mod Properties
mod_version=0.1.0
mod_id=gnomed
maven_group=io.github.sayuzaur
archives_base_name=gnomed

# Dependencies
stationapi_version=2.0.0-alpha.6.4

# Extra Dependencies
gcapi_version=3.2.5
glassnetworking_version=1.0.7
alwaysmoreitems_version=1.10.4
modmenu_version=1.1.1
bhcreative_version=0.4.9
retrocommands_version=0.5.10
unitweaks_version=0.25.1
whatsthis_version=1.0.0-rc8
freecam-stapi_version=0.3.2
